### ISSUE TITLE
aptitude install

### ISSUE THREAD

**Issue by y-nk** [woodruffw/toml2json#330]
readme does not mention. is `apt-get install toml2json` possible? (it'd be for use in github-action)

**Comment by woodruffw** [comment]
> is `apt-get install toml2json` possible? (it'd be for use in github-action)

I don't believe Debian or Ubuntu is packaging `toml2json` yet, so no. I could add a third-party `.deb` build, but I'd prefer it if one of those two were to include it in an Apt repo directly 🙂 

In the mean time, if you want to use it in GitHub Actions, this should work (and should be pretty fast after the first build, since it's cached):

```yaml
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install toml2json
        run: cargo install toml2json
```
